name: Release
on:
    push:
        branches:
            - main
jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-node@v3
            with:
              node-version: 18
          - run: echo ${{ secrets.GITHUB_TOKEN }}
          - name: Release
            env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            run: npx semantic-release
